apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: pypsa-workflow-1
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: pypsa_image_path
        value: europe-west3-docker.pkg.dev/crucial-oven-386720/pypsa/pypsa:bc8480d5c916bb1fcd00e4023e9f4eaadf479b94
      - name: run_folder_name
        value: 649b3bafc4b9a410245af349/64a047cb3c93f93a94a15b42
  templates:
    - name: main
      steps:
        - - name: pypsa-workflow
            templateRef:
              name: pypsa-workflow-template
              template: pypsa-workflow
