# SPDX-FileCopyrightText:  PyPSA-Earth and PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

# Changes with respect to the base configuration file specified in run->base_config
# default value is config.tutorial.yaml
run:
  name: NG  # Name of the configuration (arbitrary string value)
  base_config: config.tutorial.yaml  # base configuration file

retrieve_databundle: # required to be "false" for nice CI test output
  show_progress: false

countries:
- NG
- MA

scenario:
  clusters: [6]

enable:
  retrieve_databundle: true
