# SPDX-FileCopyrightText:  PyPSA-Earth and PyPSA-Eur Authors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

channels:
- conda-forge
- bioconda
- gurobi
dependencies:
- python>=3.8
- pip

- pypsa>=0.21.3
# - atlite>=0.2.4  # until https://github.com/PyPSA/atlite/issues/244 is not merged
- dask
- powerplantmatching>=0.5.7
- earth-osm>=0.1.0
- atlite

  # Dependencies of the workflow itself
- xlrd
- openpyxl
- seaborn
- snakemake-minimal
- memory_profiler
- ruamel.yaml<=0.17.26
- pytables
- lxml
- numpy
- pandas
- geopandas>=0.11.0
- fiona!=1.8.22
- xarray
- netcdf4
- networkx
- scipy
- pydoe2
- shapely>=2
- pre-commit
- pyomo
- matplotlib<=3.5.2
- reverse-geocode
- country_converter
  
  # GIS dependencies:
- cartopy
- descartes
- rasterio!=1.2.10
- rioxarray

  # PyPSA-Eur-Sec Dependencies
- geopy
- tqdm
- pytz
- country_converter

  # solvers
- glpk
- ipopt<3.13.3
- gurobi

- pip:
  - git+https://github.com/davide-f/google-drive-downloader@master  # google drive with fix for virus scan
  - git+https://github.com/FRESNA/vresutils@master  # until new pip release > 0.3.1 (strictly)
  - tsam>=1.1.0
  - chaospy  # lastest version only available on pip
