name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Push to GCR GitHub Action
      uses: RafikFarhad/push-to-gcr-github-action@v4.1
      with:
        gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
        registry: europe-central2-docker.pkg.dev
        project_id: crucial-oven-386720
        image_name: pypsa-workflow/pypsa
        image_tag: ${{ github.sha }}
        dockerfile: ./conda.Dockerfile
        